SECRET_KEY = 'REPLACE_HERE'
JWT_SECRET_KEY = 'REPLACE_HERE'

GOOGLE_CLIENT_ID = 'REPLACE_HERE'
GOOGLE_CLIENT_SECRET = 'REPLACE_HERE'

SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'
SQLALCHEMY_TRACK_MODIFICATIONS = False

AUTH_REDIRECT_URL = 'http://127.0.0.1:5000/'
